05-orm-with-view/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/',views.new,name='new'),
    path('create/',views.create,name='create'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    path('<int:pk>/update/',views.update,name='update'),
]

05-orm-with-view/articles/views.py
from django.shortcuts import render,redirect  # 여기 추가 해줘야함
from .models import Article


# 메인 페이지를 응답하는 함수 (+ 전체 게시글 목록)
def index(request):
    # DB에 전체 게시글 요청 후 가져오기
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# 특정 단일 게시글의 상세페이지를 응답(+단일 게시글 조회)
def detail(request, pk):
    # pk로 들어온 정수 값을 활용해 db에 id가 pk인 게시글을 조회 요청
    article = Article.objects.get(pk=pk)
    print(article)
    context = {
        'article' : article,
    }
    return render(request,'articles/detail.html',context)    

# 게시글을 작성하기 위한 페이지를 제공하는 함수
def new(request):
    return render(request,'articles/new.html')

# 사용자로부터 데이터를 받아 저장하고 저장이 완료 되었다는 페이지를 제공하는 함수
def create(request):
    # 사용자로부터 받은 데이터 추출
    # print(request.GET)  # <QueryDict: {'title': ['ssafy'], 'content': ['python']}>
    title = request.POST.get('title')
    content = request.POST.get('content')

    # db에 저장요청(3가지 방법)
    # 1. 
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # 2.
    article = Article(title =title, content = content)
    article.save()

    # 3. 
    # Article.objects.create(title=title, content = content)
    
    # return render(request,'articles/create.html')
    return redirect('articles:detail', article.pk)

def delete(request, pk):
    # 어떤 게시글을 지우는지 먼저 조회
    article = Article.objects.get(pk=pk)
    # db에 삭제 요청
    article.delete()
    return redirect('articles:index')

def edit(request,pk):
    #몇 번 게시글 정보를 보여줄 지 조회
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request,pk):
    # 어떤 글을 수정하는지 먼저 조회
    article = Article.objects.get(pk=pk)

    # 사용자 입력 데이터를 기존 인스턴스 변수에 새로 갱신
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()

    return redirect('articles:detail', article.pk)

05-orm-with-view/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>게시글이 문제없이 작성되었습니다</h1>
</body>
</html>

05-orm-with-view/articles/templates/articles/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>DETAIL</h1>
  <h2>{{article.pk}}</h2>
  <hr>
  <p>제목: {{article.title}}</p>
  <p>내용: {{article.content}}</p>
  <p>작성일: {{article.created_at}}</p>
  <p>수정일: {{article.updated_at}}</p>
  <hr>
  <a href="{% url "articles:edit" article.pk %}">[edit]</a>
  <form action="{% url "articles:delete" article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value ="삭제">
  </form>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>

05-orm-with-view/articles/templates/articles/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>EDIT</h1>
  <form action="{% url "articles:update" article.pk %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title" value="{{article.title}}">
    </div>
    <div>
      <label for="content">Content: </label>
      <textarea name="content" id="content">{{article.content}}</textarea>
    </div>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:detail" article.pk %}">[back]</a>
</body>
</html>

05-orm-with-view/articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Articles</h1>
  <hr>
  {% comment %} 전체 게시글 출력 {% endcomment %}
  {% for article in articles %}
  <a href="{% url "articles:detail" article.pk %}">
    <p>글 번호: {{ article.pk }}</p>
  </a>
    
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <hr>
  {% endfor %}
</body>
</html>

05-orm-with-view/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>NEW</h1>
  <form action="{% url "articles:create" %}" method="POST">
    {% csrf_token %}
    <div>
      <label for="title">Title: </label>
      <input type="text" name="title" id="title">
    </div>
    <div>
      <label for="content">Content: </label>
      <textarea name="content" id="content"></textarea>
    </div>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url "articles:index" %}">[back]</a>
</body>
</html>