database/03-02-many-to-many-relationships/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('profile/<username>/',views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

database/03-02-many-to-many-relationships/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name="change_password"),
]

database/03-02-many-to-many-relationships/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

database/03-02-many-to-many-relationships/articles/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    """
    M:N관계 설정 시 그냥 복수형으로 이름을 짓는 것 보다,
    지금 우리가 만드는 기능이 무엇인지 생각해보고 명시적인 매니저 이름을 설정하는 것이 좋다.
    
    게시글 1번에 좋아요를 누른 모든 유저 조회
    (Article -> User / 참조)

    `게시글1.users.all()` 표현을 다음과 같이 표현하는 것이 더 적합하다. 
    `게시글1.like_users.all()`
    """
    """
    [역참조 매니저 이름 충돌 상황]
    - Article : User (N:1)
        - article.user (참조)
        - user.article_set (역참조)
    - Article : User (N:M)
        - article.like_users (참조)
        - user.article_set  (역참조)
        - user.like_articles (새로운 역참조 이름으로 변경)
    - N:1 관계의 역참조 이름(_set)은 바꾸지 않는 것을 권장한다.
        - 개발 시 _set 이름만 봤을 때 "아 지금  N:1에서 역참조를 하는것이구나"를 명시적으로 알기 위함이다.
    """
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

database/03-02-many-to-many-relationships/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'email',
        )

database/03-02-many-to-many-relationships/accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import redirect, render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def delete(request):
    request.user.delete()
    return redirect('articles:index')


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

def profile(request,username):
    User = get_user_model()
    person = User.objects.get(username = username)
    
    context = {
        'person':person
    }
    
    return render(request,'accounts/profile.html',context)

def follow(request, user_pk):
    
    User = get_user_model()
    person = User.objects.get(pk = user_pk)
    
    # 셀프 follow 막기 위해 현재 요청 user와 프로필 유저 같지 않은 경우만 follow기능 동작
    if person != request.user:
        # follow함수에서 두 가지 기능을 모두 구현
        # 이미 팔로우를 한 상대 -> 언팔
        # 아직 팔로우 안한 상태 -> 팔로우
        # 팔로우 여부를 어떻게 알까요
        
        # 이미 팔로우 한 상대
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        
        
    return redirect('accounts:profile', person.username)

database/03-02-many-to-many-relationships/accounts/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

database/03-02-many-to-many-relationships/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인</h1>
  <form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

database/03-02-many-to-many-relationships/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{person.username}}님의 프로필</h1>

    <hr>

    <h2>팔로잉 수: {{person.followings.all|length}}/ 팔로워 수 : {{person.followers.all |length}}</h2>
    {% if request.user != person %}
        <form action="{% url "accounts:follow" person.pk %}" method="post">
            {% csrf_token %}
            {% if request.user in person.followers.all%}
                <input type="submit" value="언팔로우하기">
            {% else %}
                <input type="submit" value="팔로우하기">
            {% endif %}
            
            
        </form>
    {% endif %}

    <h2>{{person.username}} 가 작성한 게시글</h2>
    {% for article in person.article_set.all %}
        <div>{{article.title}}</div>
    {% endfor %}
    <h2>{{person.username}}가 작성한 댓글</h2>
    {% for comment in person.comment_set.all %}
        <div>{{comment.content}}</div>
    {% endfor %}
    <h2>{{person.username}}가 좋아요한 게시글</h2>
    {% for article in person.like_articles.all %}
        <div>{{article.title}}</div>
    {% endfor %}
</body>
</html>

database/03-02-many-to-many-relationships/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  
</body>
</html>

database/03-02-many-to-many-relationships/accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보 수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>